#cloud-config

package_update: true
packages:
  - docker.io

write_files:
  - path: /home/ubuntu/custom_index.html
    content: |
      <!DOCTYPE html>
      <html>
      <head>
          <title>Task Status</title>
          <style>
              body {
                  font-family: 'Arial', sans-serif;
                  background: black;
                  text-align: center;
                  padding: 50px;
                  margin: 0;
                  color: white;
                  height: 100vh;
                  display: flex;
                  justify-content: center;
                  align-items: center;
                  flex-direction: column;
              }
              h1 {
                  font-size: 40px;
                  background-color: black;
                  padding: 20px 40px;
                  border-radius: 10px;
                  box-shadow: 0 4px 6px rgba(0,0,0,0.2);
                  text-shadow: 0 2px 4px rgba(0,0,0,0.3);
              }
              img {
                  margin-top: 20px;
                  border-radius: 10px;
                  box-shadow: 0 4px 6px rgba(0,0,0,0.2);
              }
          </style>
      </head>
      <body>
          <h1>The Task is Done!</h1>
          <img src="https://media.tenor.com/9_aejokMHsYAAAAd/savage-cat.gif" alt="Cool GIF">
      </body>
      </html>

runcmd:
  - curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
  - add-apt-repository "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl start docker
  - systemctl enable docker
  - docker pull nginx
  - docker run --name david-nginx -v /home/ubuntu/custom_index.html:/usr/share/nginx/html/index.html -p 80:80 -d nginx
